### ISSUE TITLE
Is there functionality in this current version?

### ISSUE THREAD

**Issue by klept0** [Maxymillion/obsidian-asana#2]
I've added this to my Obsidian and Asana but not seeing anything - is there functionality at this point or is that still being implemented?

**Comment by Maxymillion** [comment]
Thanks for trying it out, there is. When you've entered an API key in the settings (and selected your workspace). The plugin will automatically (when enabled) add titles to pasted Asana Links. 

I'm still (re)working on the following features
- Search for assigned Asana tasks (like search for files)
- Search for all tasks (^)
- When pasting a link (or selecting one from search) create page with data from the task

**Comment by Maxymillion** [comment]
(What should happen in the current version if it has been set up). I've laid most of the ground work for the other features as well, so those will be added soon.

![233866838-7e004ac6-b5c9-41c4-aaf0-72c823191a25](https://user-images.githubusercontent.com/7950495/233866886-0dc4e88b-5e12-4c14-9548-54a5587652f3.gif)

**Comment by klept0** [comment]
Ok that makes a bit more sense - I will tinker along with it and can't wait to see what you have on the other features. Thanks for all your work on this and feel free to let me know if you need some testing done
